
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./src:/app/src
    networks:
      - agent-hub-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - SECRET_KEY=${SECRET_KEY:-supersecretkey}
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - agent-hub-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - agent-hub-network

networks:
  agent-hub-network:
    driver: bridge

volumes:
  mongodb_data:
