
# Default values for agent-hub
replicaCount:
  frontend: 2
  backend: 2

image:
  frontend:
    repository: agent-hub-frontend
    tag: latest
    pullPolicy: IfNotPresent
  backend:
    repository: agent-hub-backend
    tag: latest
    pullPolicy: IfNotPresent
  mongodb:
    repository: mongo
    tag: 6.0
    pullPolicy: IfNotPresent

service:
  frontend:
    type: ClusterIP
    port: 80
    targetPort: 3000
  backend:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  mongodb:
    type: ClusterIP
    port: 27017
    targetPort: 27017

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: agent-hub.example.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: backend

resources:
  frontend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  backend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  mongodb:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

mongodb:
  persistence:
    enabled: true
    size: 10Gi
  auth:
    enabled: true
    rootPassword: ${MONGODB_ROOT_PASSWORD}

env:
  backend:
    - name: MONGODB_URL
      value: mongodb://mongodb:27017/agent-hub
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: agent-hub-secrets
          key: secret-key
